services:
  app-despesas-pessoais-dev:
    container_name: app-despesas-pessoais-dev
    image: alexfariakof/api-despesas-backend-netcore-dev-img
    logging:
        driver: json-file
        options:
            max-size: "2m"
            max-file: "1"
    build:
      context: ..
      dockerfile: Despesas.Backend/Dockerfile.development
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 42535:42535
      - 42536:42536
    volumes:
      - ./Despesas.Backend/appsettings.docker.development.json:/app/appsettings.development.json
      - ./Despesas.Backend/appsettings.docker.development.json:/app/appsettings.json
      - ./Despesas.Backend/certificate/webapi-cert.pfx:/app/certificate/webapi-cert.pfx:ro